spring:
  cloud:
    config:
      server:
        git:
          search-paths: respo # 配置文件所属目录，配置文件不能放在仓库的根目录
          uri: http://IP/liangxiaobo/MyTestSpringcloudConfig.git
          username: *** # 你的用户名
          password: *** # 你的密码
      label: master

  application:
    name: config-server
server:
  port: 8768
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/